<?php
// Create a database connection
$servername = "localhost";
$dbname = "gematriaDB";
$username = "DBuser";
$password = "NYJQZZxTbeTjwVI7";

$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    $errorMessage = "Connection failed: ". $conn->connect_error. "<br>";
    $errorMessage.= "<a href='http://forevernode.pro/app1/app1.html'>Proceed to site without database access</a><br>";
    $errorMessage.= "<a href='mailto:bumpper@gmail.com'>Report issue here</a>";
    die($errorMessage);
}

// Assign the PHP variable values from the javascript variables in app1.html that were sent over via the ajax request
$word1 = $_POST['word1'];
$gematria1 = $_POST['gematria1'];
$summation = $_POST['summation'];
$letterCount = $_POST['letterCount'];
$wordCount = $_POST['wordCount'];
$paths = $_POST['paths'];
$gatesTotal = $_POST['gatesTotal'];
$skip = $_POST['skip'];
$gematriaSkip = $_POST['gematriaSkip'];
$leap = $_POST['leap'];
$gematriaLeap = $_POST['gematriaLeap'];
$reverse = $_POST['reverse'];
$gematriaReversed = $_POST['gematriaReversed'];
$elision = $_POST['elision'];
$gematriaElision = $_POST['gematriaElision'];
$backexch = $_POST['backexch'];
$gematriaAvgadBE = $_POST['gematriaAvgadBE'];
$forexch = $_POST['forexch'];
$gematriaAvgadFE = $_POST['gematriaAvgadFE'];
$acronym = $_POST['acronym'];
$gematriaAcronym = $_POST['gematriaAcronym'];
$sofim = $_POST['sofim'];
$gematriaSofit = $_POST['gematriaSofit'];
$gematriaMiluy = $_POST['gematriaMiluy'];
$textAB = $_POST['textAB'];
$gematriaAB = $_POST['gematriaAB'];
$textSaG = $_POST['textSaG'];
$gematriaSaG = $_POST['gematriaSaG'];
$textMaH = $_POST['textMaH'];
$gematriaMaH = $_POST['gematriaMaH'];
$textBaN = $_POST['textBaN'];
$gematriaBaN = $_POST['gematriaBaN'];
$RagilValue = $_POST['RagilValue'];
$KolelValue = $_POST['KolelValue'];
$Kolel1Value = $_POST['Kolel1Value'];
$HaKlaliValue = $_POST['HaKlaliValue'];
$ReducedlValue = $_POST['ReducedlValue'];
$IntegralReducedlValue = $_POST['IntegralReducedlValue'];
$KatanValue = $_POST['KatanValue'];
$OrdinalValue = $_POST['OrdinalValue'];
$HaKadmiValue = $_POST['HaKadmiValue'];
$HaPeratiValue = $_POST['HaPeratiValue'];
//$MiluyValue = $_POST['MiluyValue'];
$AYiKBeCheR = $_POST['AYiKBeCheR'];
$gematria2AYiKBeCheR = $_POST['gematria2AYiKBeCheR'];
$ATBaSh = $_POST['ATBaSh'];
$gematria2ATBaSh = $_POST['gematria2ATBaSh'];
$ALBaM = $_POST['ALBaM'];
$gematria2ALBaM = $_POST['gematria2ALBaM'];
$AChBI = $_POST['AChBI'];
$gematria2AChBI = $_POST['gematria2AChBI'];
$AChaSBeTA = $_POST['AChaSBeTA'];
$gematria2AChaSBeTA = $_POST['gematria2AChaSBeTA'];
$ATBaCh = $_POST['ATBaCh'];
$gematria2ATBaCh = $_POST['gematria2ATBaCh'];
$ATBaCh999 = $_POST['ATBaCh999'];
$gematria2ATBaCh999 = $_POST['gematria2ATBaCh999'];
$AiYBaK = $_POST['AiYBaK'];
$gematria2AiYBaK = $_POST['gematria2AiYBaK'];
$ATzBaPh = $_POST['ATzBaPh'];
$gematria2ATzBaPh = $_POST['gematria2ATzBaPh'];
$ALBeTh = $_POST['ALBeTh'];
$gematria2ALBeTh = $_POST['gematria2ALBeTh'];
$Ofanim = $_POST['Ofanim'];
$gematria2Ofanim = $_POST['gematria2Ofanim'];
$AltATBaSh = $_POST['AltATBaSh'];
$gematria2AltATBaSh = $_POST['gematria2AltATBaSh'];
$AltAShBaR = $_POST['AltAShBaR'];
$gematria2AltAShBaR = $_POST['gematria2AltAShBaR'];
$AltARBaK = $_POST['AltARBaK'];
$gematria2AltARBaK = $_POST['gematria2AltARBaK'];
$AltAQBeTz = $_POST['AltAQBeTz'];
$gematria2AltAQBeTz = $_POST['gematria2AltAQBeTz'];
$AltEZBePh = $_POST['AltEZBePh'];
$gematria2AltEZBePh = $_POST['gematria2AltEZBePh'];
$AltAPBE = $_POST['AltAPBE'];
$gematria2AltAPBE = $_POST['gematria2AltAPBE'];
$AltAEBaS = $_POST['AltAEBaS'];
$gematria2AltAEBaS = $_POST['gematria2AltAEBaS'];
$AltASBeN = $_POST['AltASBeN'];
$gematria2AltASBeN = $_POST['gematria2AltASBeN'];
$AltANBaM = $_POST['AltANBaM'];
$gematria2AltANBaM = $_POST['gematria2AltANBaM'];
$AltAMBeL = $_POST['AltAMBeL'];
$gematria2AltAMBeL = $_POST['gematria2AltAMBeL'];
$AltELBaCh = $_POST['AltELBaCh'];
$gematria2AltELBaCh = $_POST['gematria2AltELBaCh'];
$AltAChBI = $_POST['AltAChBI'];
$gematria2AltAChBI = $_POST['gematria2AltAChBI'];
$AltAIBeT = $_POST['AltAIBeT'];
$gematria2AltAIBeT = $_POST['gematria2AltAIBeT'];
$AltATBaCh = $_POST['AltATBaCh'];
$gematria2AltATBaCh = $_POST['gematria2AltATBaCh'];
$AltAChBaZ = $_POST['AltAChBaZ'];
$gematria2AltAChBaZ = $_POST['gematria2AltAChBaZ'];
$AltAZBO = $_POST['AltAZBO'];
$gematria2AltAZBO = $_POST['gematria2AltAZBO'];
$AltAVBaH = $_POST['AltAVBaH'];
$gematria2AltAVBaH = $_POST['gematria2AltAVBaH'];
$AltAHBaD = $_POST['AltAHBaD'];
$gematria2AltAHBaD = $_POST['gematria2AltAHBaD'];
$AltADBeG = $_POST['AltADBeG'];
$gematria2AltADBeG = $_POST['gematria2AltADBeG'];
$AltAGBaB = $_POST['AltAGBaB'];
$gematria2AltAGBaB = $_POST['gematria2AltAGBaB'];
$AltABBA = $_POST['AltABBA'];
$gematria2AltABBA = $_POST['gematria2AltABBA'];
$AltAAhBaT = $_POST['AltAAhBaT'];
$gematria2AltAAhBaT = $_POST['gematria2AltAAhBaT'];
$AltABBaG = $_POST['AltABBaG'];
$gematria2AltABBaG = $_POST['gematria2AltABBaG'];
$AltAGBaD = $_POST['AltAGBaD'];
$gematria2AltAGBaD = $_POST['gematria2AltAGBaD'];
$AltADBaH = $_POST['AltADBaH'];
$gematria2AltADBaH = $_POST['gematria2AltADBaH'];
$AltAHBeV = $_POST['AltAHBeV'];
$gematria2AltAHBeV = $_POST['gematria2AltAHBeV'];
$AltAVBeZ = $_POST['AltAVBeZ'];
$gematria2AltAVBeZ = $_POST['gematria2AltAVBeZ'];
$AltAZBeCh = $_POST['AltAZBeCh'];
$gematria2AltAZBeCh = $_POST['gematria2AltAZBeCh'];
$AltAChBeT = $_POST['AltAChBeT'];
$gematria2AltAChBeT = $_POST['gematria2AltAChBeT'];
$AltATBI = $_POST['AltATBI'];
$gematria2AltATBI = $_POST['gematria2AltATBI'];
$AltAIBech = $_POST['AltAIBech'];
$gematria2AltAIBech = $_POST['gematria2AltAIBech'];
$AltAChBeL = $_POST['AltAChBeL'];
$gematria2AltAChBeL = $_POST['gematria2AltAChBeL'];
$AltELBaM = $_POST['AltELBaM'];
$gematria2AltELBaM = $_POST['gematria2AltELBaM'];
$AltAMBeN = $_POST['AltAMBeN'];
$gematria2AltAMBeN = $_POST['gematria2AltAMBeN'];
$AltANBeS = $_POST['AltANBeS'];
$gematria2AltANBeS = $_POST['gematria2AltANBeS'];
$AltASBA = $_POST['AltASBA'];
$gematria2AltASBA = $_POST['gematria2AltASBA'];
$AltAABaPh = $_POST['AltAABaPh'];
$gematria2AltAABaPh = $_POST['gematria2AltAABaPh'];
$AltAPhBaTz = $_POST['AltAPhBaTz'];
$gematria2AltAPhBaTz = $_POST['gematria2AltAPhBaTz'];
$AltATzBeQ = $_POST['AltATzBeQ'];
$gematria2AltATzBeQ = $_POST['gematria2AltATzBeQ'];
$AltAKBaR = $_POST['AltAKBaR'];
$gematria2AltAKBaR = $_POST['gematria2AltAKBaR'];
$AltARBeSh = $_POST['AltARBeSh'];
$gematria2AltARBeSh = $_POST['gematria2AltARBeSh'];
$AltAShBeT = $_POST['AltAShBeT'];
$gematria2AltAShBeT = $_POST['gematria2AltAShBeT'];
$AltATBaH = $_POST['AltATBaH'];
$gematria2AltATBaH = $_POST['gematria2AltATBaH'];

// INSERT (or UPDATE) data into the table
$sql = "INSERT INTO gematriaTable (word1, gematria1, summation, letterCount, wordCount, paths, gatesTotal, skip, gematriaSkip, leap, gematriaLeap, reverse, gematriaReversed, elision, gematriaElision, backexch, gematriaAvgadBE, forexch, gematriaAvgadFE, acronym, gematriaAcronym, sofim, gematriaSofit, gematriaMiluy, textAB, gematriaAB, textSaG, gematriaSaG, textMaH, gematriaMaH, textBaN, gematriaBaN, RagilValue, KolelValue, Kolel1Value, HaKlaliValue, ReducedlValue, IntegralReducedlValue, KatanValue, OrdinalValue, HaKadmiValue, HaPeratiValue, /*MiluyValue, */AYiKBeCheR, gematria2AYiKBeCheR, ATBaSh, gematria2ATBaSh, ALBaM, gematria2ALBaM, AChBI, gematria2AChBI, AChaSBeTA, gematria2AChaSBeTA, ATBaCh, gematria2ATBaCh, ATBaCh999, gematria2ATBaCh999, AiYBaK, gematria2AiYBaK, ATzBaPh, gematria2ATzBaPh, ALBeTh, gematria2ALBeTh, Ofanim, gematria2Ofanim, AltATBaSh, gematria2AltATBaSh, AltAShBaR, gematria2AltAShBaR, AltARBaK, gematria2AltARBaK, AltAQBeTz, gematria2AltAQBeTz, AltEZBePh, gematria2AltEZBePh, AltAPBE, gematria2AltAPBE, AltAEBaS, gematria2AltAEBaS, AltASBeN, gematria2AltASBeN, AltANBaM, gematria2AltANBaM, AltAMBeL, gematria2AltAMBeL, AltELBaCh, gematria2AltELBaCh, AltAChBI, gematria2AltAChBI, AltAIBeT, gematria2AltAIBeT, AltATBaCh, gematria2AltATBaCh, AltAChBaZ, gematria2AltAChBaZ, AltAZBO, gematria2AltAZBO, AltAVBaH, gematria2AltAVBaH, AltAHBaD, gematria2AltAHBaD, AltADBeG, gematria2AltADBeG, AltAGBaB, gematria2AltAGBaB, AltABBA, gematria2AltABBA, AltAAhBaT, gematria2AltAAhBaT, AltABBaG, gematria2AltABBaG, AltAGBaD, gematria2AltAGBaD, AltADBaH, gematria2AltADBaH, AltAHBeV, gematria2AltAHBeV, AltAVBeZ, gematria2AltAVBeZ, AltAZBeCh, gematria2AltAZBeCh, AltAChBeT, gematria2AltAChBeT, AltATBI, gematria2AltATBI, AltAIBech, gematria2AltAIBech, AltAChBeL, gematria2AltAChBeL, AltELBaM, gematria2AltELBaM, AltAMBeN, gematria2AltAMBeN, AltANBeS, gematria2AltANBeS, AltASBA, gematria2AltASBA, AltAABaPh, gematria2AltAABaPh, AltAPhBaTz, gematria2AltAPhBaTz, AltATzBeQ, gematria2AltATzBeQ, AltAKBaR, gematria2AltAKBaR, AltARBeSh, gematria2AltARBeSh, AltAShBeT, gematria2AltAShBeT, AltATBaH, gematria2AltATBaH) 
VALUES ('$word1', $gematria1, '$summation', $letterCount, $wordCount, $paths, $gatesTotal, '$skip', $gematriaSkip, '$leap', $gematriaLeap, '$reverse', $gematriaReversed, '$elision', $gematriaElision, '$backexch', $gematriaAvgadBE, '$forexch', $gematriaAvgadFE, '$acronym', $gematriaAcronym, '$sofim', $gematriaSofit, $gematriaMiluy, '$textAB', $gematriaAB, '$textSaG', $gematriaSaG, '$textMaH', $gematriaMaH, '$textBaN', $gematriaBaN, $RagilValue, $KolelValue, $Kolel1Value, $HaKlaliValue, $ReducedlValue, $IntegralReducedlValue, $KatanValue, $OrdinalValue, $HaKadmiValue, $HaPeratiValue, /*$MiluyValue, */'$AYiKBeCheR', $gematria2AYiKBeCheR, '$ATBaSh', $gematria2ATBaSh, '$ALBaM', $gematria2ALBaM, '$AChBI', $gematria2AChBI, '$AChaSBeTA', $gematria2AChaSBeTA, '$ATBaCh', $gematria2ATBaCh, '$ATBaCh999', $gematria2ATBaCh999, '$AiYBaK', $gematria2AiYBaK, '$ATzBaPh', $gematria2ATzBaPh, '$ALBeTh', $gematria2ALBeTh, '$Ofanim', $gematria2Ofanim, '$AltATBaSh', $gematria2AltATBaSh, '$AltAShBaR', $gematria2AltAShBaR, '$AltARBaK', $gematria2AltARBaK, '$AltAQBeTz', $gematria2AltAQBeTz, '$AltEZBePh', $gematria2AltEZBePh, '$AltAPBE', $gematria2AltAPBE, '$AltAEBaS', $gematria2AltAEBaS, '$AltASBeN', $gematria2AltASBeN, '$AltANBaM', $gematria2AltANBaM, '$AltAMBeL', $gematria2AltAMBeL, '$AltELBaCh', $gematria2AltELBaCh, '$AltAChBI', $gematria2AltAChBI, '$AltAIBeT', $gematria2AltAIBeT, '$AltATBaCh', $gematria2AltATBaCh, '$AltAChBaZ', $gematria2AltAChBaZ, '$AltAZBO', $gematria2AltAZBO, '$AltAVBaH', $gematria2AltAVBaH, '$AltAHBaD', $gematria2AltAHBaD, '$AltADBeG', $gematria2AltADBeG, '$AltAGBaB', $gematria2AltAGBaB, '$AltABBA', $gematria2AltABBA, '$AltAAhBaT', $gematria2AltAAhBaT, '$AltABBaG', $gematria2AltABBaG, '$AltAGBaD', $gematria2AltAGBaD, '$AltADBaH', $gematria2AltADBaH, '$AltAHBeV', $gematria2AltAHBeV, '$AltAVBeZ', $gematria2AltAVBeZ, '$AltAZBeCh', $gematria2AltAZBeCh, '$AltAChBeT', $gematria2AltAChBeT, '$AltATBI', $gematria2AltATBI, '$AltAIBech', $gematria2AltAIBech, '$AltAChBeL', $gematria2AltAChBeL, '$AltELBaM', $gematria2AltELBaM, '$AltAMBeN', $gematria2AltAMBeN, '$AltANBeS', $gematria2AltANBeS, '$AltASBA', $gematria2AltASBA, '$AltAABaPh', $gematria2AltAABaPh, '$AltAPhBaTz', $gematria2AltAPhBaTz, '$AltATzBeQ', $gematria2AltATzBeQ, '$AltAKBaR', $gematria2AltAKBaR, '$AltARBeSh', $gematria2AltARBeSh, '$AltAShBeT', $gematria2AltAShBeT, '$AltATBaH', $gematria2AltATBaH)
ON DUPLICATE KEY UPDATE word1 = VALUES(word1), gematria1 = VALUES(gematria1), summation = VALUES(summation), letterCount = VALUES(letterCount), wordCount = VALUES(wordCount), paths = VALUES(paths), gatesTotal = VALUES(gatesTotal), skip = VALUES(skip), gematriaSkip = VALUES(gematriaSkip), leap = VALUES(leap), gematriaLeap = VALUES(gematriaLeap), reverse = VALUES(reverse), gematriaReversed = VALUES(gematriaReversed), elision = VALUES(elision), gematriaElision = VALUES(gematriaElision), backexch = VALUES(backexch), gematriaAvgadBE = VALUES(gematriaAvgadBE), forexch = VALUES(forexch), gematriaAvgadFE = VALUES(gematriaAvgadFE), acronym = VALUES(acronym), gematriaAcronym = VALUES(gematriaAcronym), sofim = VALUES(sofim), gematriaSofit = VALUES(gematriaSofit), gematriaMiluy = VALUES(gematriaMiluy), textAB = VALUES(textAB), gematriaAB = VALUES(gematriaAB), textSaG = VALUES(textSaG), gematriaSaG = VALUES(gematriaSaG), textMaH = VALUES(textMaH), gematriaMaH = VALUES(gematriaMaH), textBaN = VALUES(textBaN), gematriaBaN = VALUES(gematriaBaN), RagilValue = VALUES(RagilValue), KolelValue = VALUES(KolelValue), Kolel1Value = VALUES(Kolel1Value), HaKlaliValue = VALUES(HaKlaliValue), ReducedlValue = VALUES(ReducedlValue), IntegralReducedlValue = VALUES(IntegralReducedlValue), KatanValue = VALUES(KatanValue), OrdinalValue = VALUES(OrdinalValue), HaKadmiValue = VALUES(HaKadmiValue), HaPeratiValue = VALUES(HaPeratiValue), /*MiluyValue = VALUES(MiluyValue), */AYiKBeCheR = VALUES(AYiKBeCheR), gematria2AYiKBeCheR = VALUES(gematria2AYiKBeCheR), ATBaSh = VALUES(ATBaSh), gematria2ATBaSh = VALUES(gematria2ATBaSh), ALBaM = VALUES(ALBaM), gematria2ALBaM = VALUES(gematria2ALBaM), AChBI = VALUES(AChBI), gematria2AChBI = VALUES(gematria2AChBI), AChaSBeTA = VALUES(AChaSBeTA), gematria2AChaSBeTA = VALUES(gematria2AChaSBeTA), ATBaCh = VALUES(ATBaCh), gematria2ATBaCh = VALUES(gematria2ATBaCh), ATBaCh999 = VALUES(ATBaCh999), gematria2ATBaCh999 = VALUES(gematria2ATBaCh999), AiYBaK = VALUES(AiYBaK), gematria2AiYBaK = VALUES(gematria2AiYBaK), ATzBaPh = VALUES(ATzBaPh), gematria2ATzBaPh = VALUES(gematria2ATzBaPh), ALBeTh = VALUES(ALBeTh), gematria2ALBeTh = VALUES(gematria2ALBeTh), Ofanim = VALUES(Ofanim), gematria2Ofanim = VALUES(gematria2Ofanim), AltATBaSh = VALUES(AltATBaSh), gematria2AltATBaSh = VALUES(gematria2AltATBaSh), AltAShBaR = VALUES(AltAShBaR), gematria2AltAShBaR = VALUES(gematria2AltAShBaR), AltARBaK = VALUES(AltARBaK), gematria2AltARBaK = VALUES(gematria2AltARBaK), AltAQBeTz = VALUES(AltAQBeTz), gematria2AltAQBeTz = VALUES(gematria2AltAQBeTz), AltEZBePh = VALUES(AltEZBePh), gematria2AltEZBePh = VALUES(gematria2AltEZBePh), AltAPBE = VALUES(AltAPBE), gematria2AltAPBE = VALUES(gematria2AltAPBE), AltAEBaS = VALUES(AltAEBaS), gematria2AltAEBaS = VALUES(gematria2AltAEBaS), AltASBeN = VALUES(AltASBeN), gematria2AltASBeN = VALUES(gematria2AltASBeN), AltANBaM = VALUES(AltANBaM), gematria2AltANBaM = VALUES(gematria2AltANBaM), AltAMBeL = VALUES(AltAMBeL), gematria2AltAMBeL = VALUES(gematria2AltAMBeL), AltELBaCh = VALUES(AltELBaCh), gematria2AltELBaCh = VALUES(gematria2AltELBaCh), AltAChBI = VALUES(AltAChBI), gematria2AltAChBI = VALUES(gematria2AltAChBI), AltAIBeT = VALUES(AltAIBeT), gematria2AltAIBeT = VALUES(gematria2AltAIBeT), AltATBaCh = VALUES(AltATBaCh), gematria2AltATBaCh = VALUES(gematria2AltATBaCh), AltAChBaZ = VALUES(AltAChBaZ), gematria2AltAChBaZ = VALUES(gematria2AltAChBaZ), AltAZBO = VALUES(AltAZBO), gematria2AltAZBO = VALUES(gematria2AltAZBO), AltAVBaH = VALUES(AltAVBaH), gematria2AltAVBaH = VALUES(gematria2AltAVBaH), AltAHBaD = VALUES(AltAHBaD), gematria2AltAHBaD = VALUES(gematria2AltAHBaD), AltADBeG = VALUES(AltADBeG), gematria2AltADBeG = VALUES(gematria2AltADBeG), AltAGBaB = VALUES(AltAGBaB), gematria2AltAGBaB = VALUES(gematria2AltAGBaB), AltABBA = VALUES(AltABBA), gematria2AltABBA = VALUES(gematria2AltABBA), AltAAhBaT = VALUES(AltAAhBaT), gematria2AltAAhBaT = VALUES(gematria2AltAAhBaT), AltABBaG = VALUES(AltABBaG), gematria2AltABBaG = VALUES(gematria2AltABBaG), AltAGBaD = VALUES(AltAGBaD), gematria2AltAGBaD = VALUES(gematria2AltAGBaD), AltADBaH = VALUES(AltADBaH), gematria2AltADBaH = VALUES(gematria2AltADBaH), AltAHBeV = VALUES(AltAHBeV), gematria2AltAHBeV = VALUES(gematria2AltAHBeV), AltAVBeZ = VALUES(AltAVBeZ), gematria2AltAVBeZ = VALUES(gematria2AltAVBeZ), AltAZBeCh = VALUES(AltAZBeCh), gematria2AltAZBeCh = VALUES(gematria2AltAZBeCh), AltAChBeT = VALUES(AltAChBeT), gematria2AltAChBeT = VALUES(gematria2AltAChBeT), AltATBI = VALUES(AltATBI), gematria2AltATBI = VALUES(gematria2AltATBI), AltAIBech = VALUES(AltAIBech), gematria2AltAIBech = VALUES(gematria2AltAIBech), AltAChBeL = VALUES(AltAChBeL), gematria2AltAChBeL = VALUES(gematria2AltAChBeL), AltELBaM = VALUES(AltELBaM), gematria2AltELBaM = VALUES(gematria2AltELBaM), AltAMBeN = VALUES(AltAMBeN), gematria2AltAMBeN = VALUES(gematria2AltAMBeN), AltANBeS = VALUES(AltANBeS), gematria2AltANBeS = VALUES(gematria2AltANBeS), AltASBA = VALUES(AltASBA), gematria2AltASBA = VALUES(gematria2AltASBA), AltAABaPh = VALUES(AltAABaPh), gematria2AltAABaPh = VALUES(gematria2AltAABaPh), AltAPhBaTz = VALUES(AltAPhBaTz), gematria2AltAPhBaTz = VALUES(gematria2AltAPhBaTz), AltATzBeQ = VALUES(AltATzBeQ), gematria2AltATzBeQ = VALUES(gematria2AltATzBeQ), AltAKBaR = VALUES(AltAKBaR), gematria2AltAKBaR = VALUES(gematria2AltAKBaR), AltARBeSh = VALUES(AltARBeSh), gematria2AltARBeSh = VALUES(gematria2AltARBeSh), AltAShBeT = VALUES(AltAShBeT), gematria2AltAShBeT = VALUES(gematria2AltAShBeT), AltATBaH = VALUES(AltATBaH), gematria2AltATBaH = VALUES(gematria2AltATBaH)";

// Retrieve data from the table if it matches variable $gematria1.  Then include all items from that row. 
if ($conn->query($sql) === TRUE) {
    // Retrieve data from the table
    $sql = "SELECT * FROM gematriaTable WHERE gematria1 = '$gematria1'";
    $result = $conn->query($sql);
    if ($result->num_rows > 0) {
        // Output data in an HTML table structure
        echo "<div id='result' class='result'><table cellpadding='3' cellspacing='0' border='1' align='center'>";
        // Add header row
        echo "<tr>";
        echo "<th style='background-color: #0282b5 !important;' class='small-font'>Gematria <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Word <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Summation <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Letter Count <br>&nbsp;</th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Word Count <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Paths <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Gates <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Skip <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Skip Value <br>&nbsp;</th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Leap <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Leap Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Reversed <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Reversed Value <br>&nbsp;</th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Elision <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Elision Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Back Exchange <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Back Exchange Value </th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Forward Exchange <br>&nbsp;</th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Forward Exchange Value </th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Acronym <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Acronym Value <br>&nbsp;</th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Sofim <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #3d4745 !important;' class='small-font'>Sofim Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Miluy Value <br>&nbsp;</th>";
        echo "<th style='background-color: #2f3d42 !important;' class='small-font'>AB Spelling <br>&nbsp;</th>";
        echo "<th style='background-color: #2f3d42 !important;' class='small-font'>AB Value <br>&nbsp;</th>";
        echo "<th style='background-color: #312f42 !important;' class='small-font'>SaG Spealling <br>&nbsp;</th>";
        echo "<th style='background-color: #312f42 !important;' class='small-font'>SaG Value <br>&nbsp;</th>";
        echo "<th style='background-color: #2f3d42 !important;' class='small-font'>MaH Spelling <br>&nbsp;</th>";
        echo "<th style='background-color: #2f3d42 !important;' class='small-font'>MaH Value <br>&nbsp;</th>";
        echo "<th style='background-color: #312f42 !important;' class='small-font'>BaN Spelling <br>&nbsp;</th>";
        echo "<th style='background-color: #312f42 !important;' class='small-font'>BaN Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Ragil Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Kolel Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Kolel(+word) Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>HaKlali Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Reduced Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Integral Reduced Value</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Katan Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>Ordinal Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>HaKadmi Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>HaPerati Value <br>&nbsp;</th>";
        //echo "<th style='background-color: #47494a !important;' class='small-font'>Miluy Value <br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>AYiKBeCheR <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>AYiKBeCheR Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>ATBaSh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>ATBaSh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>ALBaM <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>ALBaM Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AChBI <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AChBI Value <br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>AChaSBeTA <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>AChaSBeTA Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>ATBaCh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>ATBaCh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>ATBaCh Finals <br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>ATBaCh Finals Value </th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AiYBaK <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AiYBaK Value <br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>ATzBaPh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>ATzBaPh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>ALBeTh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>ALBeTh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>Ofanim <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #1e2738 !important;' class='small-font'>Ofanim Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltATBaSh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltATBaSh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAShBaR <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAShBaR Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltARBaK <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltARBaK Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAQBeTz <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAQBeTz Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltEZBePh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltEZBePh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAPBE <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAPBE Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAEBaS <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAEBaS Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltASBeN <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltASBeN Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltANBaM <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltANBaM Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAMBeL <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAMBeL Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltELBaCh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltELBaCh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAChBI <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAChBI Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAIBeT <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAIBeT Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltATBaCh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltATBaCh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAChBaZ <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAChBaZ Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAZBO <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAZBO Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAVBaH <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAVBaH Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAHBaD <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAHBaD Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltADBeG <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltADBeG Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAGBaB <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAGBaB Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltABBA <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltABBA Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAAhBaT <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAAhBaT Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltABBaG <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltABBaG Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAGBaD <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAGBaD Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltADBaH <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltADBaH Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAHBeV <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAHBeV Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAVBeZ <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAVBeZ Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAZBeCh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAZBeCh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAChBeT <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAChBeT Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltATBI <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltATBI Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAIBech <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAIBech Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAChBeL <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAChBeL Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltELBaM <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltELBaM Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAMBeN <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAMBeN Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltANBeS <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltANBeS Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltASBA <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltASBA Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAABaPh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltAABaPh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAPhBaTz <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAPhBaTz Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltATzBeQ <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltATzBeQ Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAKBaR <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAKBaR Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltARBeSh <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltARBeSh Value <br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAShBeT <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #47494a !important;' class='small-font'>AltAShBeT Value <br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltATBaH <br>&nbsp;<br>&nbsp;</th>";
        echo "<th style='background-color: #381e1e !important;' class='small-font'>AltATBaH Value <br>&nbsp;</th>";
        echo "</tr></p>";
        while($row = $result->fetch_assoc()) {
            echo "<tr>";
            echo "<td style='background-color: #0282b5 !important;' class='small-font'><a href='". urlencode($row["gematria1"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria1"]). "'); Transpose();\">". htmlspecialchars($row["gematria1"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["word1"]). "' target='_blank'>". htmlspecialchars($row["word1"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["summation"]). "' target='_blank'>". htmlspecialchars($row["summation"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["letterCount"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["letterCount"]). "'); Transpose();\">". htmlspecialchars($row["letterCount"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='". urlencode($row["wordCount"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["wordCount"]). "'); Transpose();\">". htmlspecialchars($row["wordCount"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["paths"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["paths"]). "'); Transpose();\">". htmlspecialchars($row["paths"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='". urlencode($row["gatesTotal"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gatesTotal"]). "'); Transpose();\">". htmlspecialchars($row["gatesTotal"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["skip"]). "' target='_blank'>". htmlspecialchars($row["skip"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematriaSkip"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaSkip"]). "'); Transpose();\">". htmlspecialchars($row["gematriaSkip"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["leap"]). "' target='_blank'>". htmlspecialchars($row["leap"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='". urlencode($row["gematriaLeap"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaLeap"]). "'); Transpose();\">". htmlspecialchars($row["gematriaLeap"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["reverse"]). "' target='_blank'>". htmlspecialchars($row["reverse"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematriaReversed"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaReversed"]). "'); Transpose();\">". htmlspecialchars($row["gematriaReversed"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["elision"]). "' target='_blank'>". htmlspecialchars($row["elision"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='". urlencode($row["gematriaElision"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaElision"]). "'); Transpose();\">". htmlspecialchars($row["gematriaElision"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["backexch"]). "' target='_blank'>". htmlspecialchars($row["backexch"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematriaAvgadBE"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaAvgadBE"]). "'); Transpose();\">". htmlspecialchars($row["gematriaAvgadBE"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["forexch"]). "' target='_blank'>". htmlspecialchars($row["forexch"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='". urlencode($row["gematriaAvgadFE"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaAvgadFE"]). "'); Transpose();\">". htmlspecialchars($row["gematriaAvgadFE"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["acronym"]). "' target='_blank'>". htmlspecialchars($row["acronym"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematriaAcronym"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaAcronym"]). "'); Transpose();\">". htmlspecialchars($row["gematriaAcronym"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["sofim"]). "' target='_blank'>". htmlspecialchars($row["sofim"]). "</a></td>";
            echo "<td style='background-color: #3d4745 !important;' class='small-font'><a href='". urlencode($row["gematriaSofit"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaSofit"]). "'); Transpose();\">". htmlspecialchars($row["gematriaSofit"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematriaMiluy"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaMiluy"]). "'); Transpose();\">". htmlspecialchars($row["gematriaMiluy"]). "</a></td>";
            echo "<td style='background-color: #2f3d42 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["textAB"]). "' target='_blank'>". htmlspecialchars($row["textAB"]). "</a></td>";
            echo "<td style='background-color: #2f3d42 !important;' class='small-font'><a href='". urlencode($row["gematriaAB"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaAB"]). "'); Transpose();\">". htmlspecialchars($row["gematriaAB"]). "</a></td>";
            echo "<td style='background-color: #312f42 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["textSaG"]). "' target='_blank'>". htmlspecialchars($row["textSaG"]). "</a></td>";
            echo "<td style='background-color: #312f42 !important;' class='small-font'><a href='". urlencode($row["gematriaSaG"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaSaG"]). "'); Transpose();\">". htmlspecialchars($row["gematriaSaG"]). "</a></td>";
            echo "<td style='background-color: #2f3d42 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["textMaH"]). "' target='_blank'>". htmlspecialchars($row["textMaH"]). "</a></td>";
            echo "<td style='background-color: #2f3d42 !important;' class='small-font'><a href='". urlencode($row["gematriaMaH"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaMaH"]). "'); Transpose();\">". htmlspecialchars($row["gematriaMaH"]). "</a></td>";
            echo "<td style='background-color: #312f42 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["textBaN"]). "' target='_blank'>". htmlspecialchars($row["textBaN"]). "</a></td>";
            echo "<td style='background-color: #312f42 !important;' class='small-font'><a href='". urlencode($row["gematriaBaN"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematriaBaN"]). "'); Transpose();\">". htmlspecialchars($row["gematriaBaN"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["RagilValue"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["RagilValue"]). "'); Transpose();\">". htmlspecialchars($row["RagilValue"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["KolelValue"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["KolelValue"]). "'); Transpose();\">". htmlspecialchars($row["KolelValue"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["Kolel1Value"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["Kolel1Value"]). "'); Transpose();\">". htmlspecialchars($row["Kolel1Value"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["HaKlaliValue"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["HaKlaliValue"]). "'); Transpose();\">". htmlspecialchars($row["HaKlaliValue"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["ReducedlValue"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["ReducedlValue"]). "'); Transpose();\">". htmlspecialchars($row["ReducedlValue"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["IntegralReducedlValue"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["IntegralReducedlValue"]). "'); Transpose();\">". htmlspecialchars($row["IntegralReducedlValue"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["KatanValue"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["KatanValue"]). "'); Transpose();\">". htmlspecialchars($row["KatanValue"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["OrdinalValue"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["OrdinalValue"]). "'); Transpose();\">". htmlspecialchars($row["OrdinalValue"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["HaKadmiValue"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["HaKadmiValue"]). "'); Transpose();\">". htmlspecialchars($row["HaKadmiValue"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["HaPeratiValue"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["HaPeratiValue"]). "'); Transpose();\">". htmlspecialchars($row["HaPeratiValue"]). "</a></td>";
            //echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["MiluyValue"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["MiluyValue"]). "'); Transpose();\">". htmlspecialchars($row["MiluyValue"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AYiKBeCheR"]). "' target='_blank'>". htmlspecialchars($row["AYiKBeCheR"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='". urlencode($row["gematria2AYiKBeCheR"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AYiKBeCheR"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AYiKBeCheR"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["ATBaSh"]). "' target='_blank'>". htmlspecialchars($row["ATBaSh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2ATBaSh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2ATBaSh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2ATBaSh"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["ALBaM"]). "' target='_blank'>". htmlspecialchars($row["ALBaM"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='". urlencode($row["gematria2ALBaM"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2ALBaM"]). "'); Transpose();\">". htmlspecialchars($row["gematria2ALBaM"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AChBI"]). "' target='_blank'>". htmlspecialchars($row["AChBI"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AChBI"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AChBI"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AChBI"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AChaSBeTA"]). "' target='_blank'>". htmlspecialchars($row["AChaSBeTA"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='". urlencode($row["gematria2AChaSBeTA"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AChaSBeTA"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AChaSBeTA"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["ATBaCh"]). "' target='_blank'>". htmlspecialchars($row["ATBaCh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2ATBaCh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2ATBaCh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2ATBaCh"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["ATBaCh999"]). "' target='_blank'>". htmlspecialchars($row["ATBaCh999"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='". urlencode($row["gematria2ATBaCh999"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2ATBaCh999"]). "'); Transpose();\">". htmlspecialchars($row["gematria2ATBaCh999"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AiYBaK"]). "' target='_blank'>". htmlspecialchars($row["AiYBaK"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AiYBaK"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AiYBaK"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AiYBaK"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["ATzBaPh"]). "' target='_blank'>". htmlspecialchars($row["ATzBaPh"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='". urlencode($row["gematria2ATzBaPh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2ATzBaPh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2ATzBaPh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["ALBeTh"]). "' target='_blank'>". htmlspecialchars($row["ALBeTh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2ALBeTh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2ALBeTh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2ALBeTh"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["Ofanim"]). "' target='_blank'>". htmlspecialchars($row["Ofanim"]). "</a></td>";
            echo "<td style='background-color: #1e2738 !important;' class='small-font'><a href='". urlencode($row["gematria2Ofanim"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2Ofanim"]). "'); Transpose();\">". htmlspecialchars($row["gematria2Ofanim"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltATBaSh"]). "' target='_blank'>". htmlspecialchars($row["AltATBaSh"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltATBaSh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltATBaSh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltATBaSh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAShBaR"]). "' target='_blank'>". htmlspecialchars($row["AltAShBaR"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAShBaR"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAShBaR"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAShBaR"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltARBaK"]). "' target='_blank'>". htmlspecialchars($row["AltARBaK"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltARBaK"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltARBaK"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltARBaK"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAQBeTz"]). "' target='_blank'>". htmlspecialchars($row["AltAQBeTz"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAQBeTz"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAQBeTz"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAQBeTz"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltEZBePh"]). "' target='_blank'>". htmlspecialchars($row["AltEZBePh"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltEZBePh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltEZBePh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltEZBePh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAPBE"]). "' target='_blank'>". htmlspecialchars($row["AltAPBE"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAPBE"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAPBE"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAPBE"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAEBaS"]). "' target='_blank'>". htmlspecialchars($row["AltAEBaS"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltAEBaS"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAEBaS"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAEBaS"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltASBeN"]). "' target='_blank'>". htmlspecialchars($row["AltASBeN"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltASBeN"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltASBeN"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltASBeN"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltANBaM"]). "' target='_blank'>". htmlspecialchars($row["AltANBaM"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltANBaM"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltANBaM"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltANBaM"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAMBeL"]). "' target='_blank'>". htmlspecialchars($row["AltAMBeL"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAMBeL"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAMBeL"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAMBeL"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltELBaCh"]). "' target='_blank'>". htmlspecialchars($row["AltELBaCh"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltELBaCh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltELBaCh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltELBaCh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAChBI"]). "' target='_blank'>". htmlspecialchars($row["AltAChBI"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAChBI"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAChBI"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAChBI"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAIBeT"]). "' target='_blank'>". htmlspecialchars($row["AltAIBeT"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltAIBeT"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAIBeT"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAIBeT"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltATBaCh"]). "' target='_blank'>". htmlspecialchars($row["AltATBaCh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltATBaCh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltATBaCh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltATBaCh"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAChBaZ"]). "' target='_blank'>". htmlspecialchars($row["AltAChBaZ"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltAChBaZ"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAChBaZ"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAChBaZ"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAZBO"]). "' target='_blank'>". htmlspecialchars($row["AltAZBO"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAZBO"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAZBO"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAZBO"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAVBaH"]). "' target='_blank'>". htmlspecialchars($row["AltAVBaH"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltAVBaH"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAVBaH"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAVBaH"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAHBaD"]). "' target='_blank'>". htmlspecialchars($row["AltAHBaD"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAHBaD"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAHBaD"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAHBaD"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltADBeG"]). "' target='_blank'>". htmlspecialchars($row["AltADBeG"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltADBeG"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltADBeG"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltADBeG"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAGBaB"]). "' target='_blank'>". htmlspecialchars($row["AltAGBaB"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAGBaB"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAGBaB"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAGBaB"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltABBA"]). "' target='_blank'>". htmlspecialchars($row["AltABBA"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltABBA"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltABBA"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltABBA"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAAhBaT"]). "' target='_blank'>". htmlspecialchars($row["AltAAhBaT"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAAhBaT"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAAhBaT"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAAhBaT"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltABBaG"]). "' target='_blank'>". htmlspecialchars($row["AltABBaG"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltABBaG"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltABBaG"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltABBaG"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAGBaD"]). "' target='_blank'>". htmlspecialchars($row["AltAGBaD"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAGBaD"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAGBaD"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAGBaD"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltADBaH"]). "' target='_blank'>". htmlspecialchars($row["AltADBaH"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltADBaH"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltADBaH"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltADBaH"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAHBeV"]). "' target='_blank'>". htmlspecialchars($row["AltAHBeV"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAHBeV"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAHBeV"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAHBeV"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAVBeZ"]). "' target='_blank'>". htmlspecialchars($row["AltAVBeZ"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltAVBeZ"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAVBeZ"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAVBeZ"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAZBeCh"]). "' target='_blank'>". htmlspecialchars($row["AltAZBeCh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAZBeCh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAZBeCh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAZBeCh"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAChBeT"]). "' target='_blank'>". htmlspecialchars($row["AltAChBeT"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltAChBeT"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAChBeT"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAChBeT"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltATBI"]). "' target='_blank'>". htmlspecialchars($row["AltATBI"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltATBI"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltATBI"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltATBI"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAIBech"]). "' target='_blank'>". htmlspecialchars($row["AltAIBech"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltAIBech"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAIBech"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAIBech"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAChBeL"]). "' target='_blank'>". htmlspecialchars($row["AltAChBeL"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAChBeL"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAChBeL"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAChBeL"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltELBaM"]). "' target='_blank'>". htmlspecialchars($row["AltELBaM"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltELBaM"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltELBaM"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltELBaM"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAMBeN"]). "' target='_blank'>". htmlspecialchars($row["AltAMBeN"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAMBeN"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAMBeN"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAMBeN"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltANBeS"]). "' target='_blank'>". htmlspecialchars($row["AltANBeS"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltANBeS"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltANBeS"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltANBeS"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltASBA"]). "' target='_blank'>". htmlspecialchars($row["AltASBA"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltASBA"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltASBA"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltASBA"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAABaPh"]). "' target='_blank'>". htmlspecialchars($row["AltAABaPh"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltAABaPh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAABaPh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAABaPh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAPhBaTz"]). "' target='_blank'>". htmlspecialchars($row["AltAPhBaTz"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAPhBaTz"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAPhBaTz"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAPhBaTz"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltATzBeQ"]). "' target='_blank'>". htmlspecialchars($row["AltATzBeQ"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltATzBeQ"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltATzBeQ"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltATzBeQ"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAKBaR"]). "' target='_blank'>". htmlspecialchars($row["AltAKBaR"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAKBaR"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAKBaR"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAKBaR"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltARBeSh"]). "' target='_blank'>". htmlspecialchars($row["AltARBeSh"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltARBeSh"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltARBeSh"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltARBeSh"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltAShBeT"]). "' target='_blank'>". htmlspecialchars($row["AltAShBeT"]). "</a></td>";
            echo "<td style='background-color: #47494a !important;' class='small-font'><a href='". urlencode($row["gematria2AltAShBeT"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltAShBeT"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltAShBeT"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='http://translate.google.com/#auto/en/". urlencode($row["AltATBaH"]). "' target='_blank'>". htmlspecialchars($row["AltATBaH"]). "</a></td>";
            echo "<td style='background-color: #381e1e !important;' class='small-font'><a href='". urlencode($row["gematria2AltATBaH"]). "' onClick=\"replaceInputField('inputText', '". htmlspecialchars($row["gematria2AltATBaH"]). "'); Transpose();\">". htmlspecialchars($row["gematria2AltATBaH"]). "</a></td>";
            echo "</tr></div>";
        }
        echo "</table><img src=\"img/invis.gif\" height=\"5\" width=\"0\" border=\"0\">";
    } else {
        echo "No matches found";
    }
} else {
    echo "Error: ". $sql. "<br>". $conn->error;
}

$conn->close();
?>