/*
 * JS for startScreen generated by Tiggzi
 *
 * Created on: Tuesday, February 19, 2013, 06:12:17 PM (PST)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '68cc11ff-15ad-4b66-84f4-1fb4bbb8ddce';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var RESTService = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "startScreen",
    "location": "#j_0"
}];
j_0_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'input': 'j_4',
        'gematria1': 'j_8',
        'cryptographyMenu': 'j_10',
        'mobileselectmenuitem1': 'j_11',
        'gematriaMenu': 'j_6',
        'mobileselectmenuitem1': 'j_7',
        'transposeButton': 'j_9',
        'cryptography': 'j_5',
        'gematria2': 'j_12'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_0';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_0_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_0';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_3671_onLoad = j_0_onLoad = function() {
        screen_3671_elementsExtraJS();
        j_0_windowEvents();
        screen_3671_elementsEvents();
    }
    // screen window events
    screen_3671_windowEvents = j_0_windowEvents = function() {
        $('#j_0').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_3671_elementsExtraJS = j_0_elementsExtraJS = function() {
        // screen (screen-3671) extra code
        /* cryptographyMenu */
        $("#j_10").parent().find("a.ui-btn").attr("tabindex", "2"); /* gematriaMenu */
        $("#j_6").parent().find("a.ui-btn").attr("tabindex", "3");
    }
    // screen elements handler
    screen_3671_elementsEvents = j_0_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_3 [name="transposeButton"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    var c = char;
                    var cryptography = cryptographyMenu;
                    var gematria = gematriaMenu;
                    var value = valueMenu; //whatever option in the value menu is selected will be the VALUE varialbe
                    var string = inputText; //capture what is entered in the input text box as variable STRING
                    string.replace(/\s/g, "") //remove white spaces from the text entered
                    var n = string.split(""); //STRING will be split up by charter or letter
                    char[] chars = string.Array(); //each charter will put into it's own segment of the array
                    var l = int //integer placeholder for totla number of charters in STRING
                    l = Array.length //find total number of charter in STRING
                    //transpose charters based on which of the 7 types of Encryption selected from the cryptMenu
                    if (cryptography = Al - bam) {
                        switch (Array[c]) {
                        case 'a':
                            document.write("z");
                        case 'b':
                            document.write("y");
                        case 'c':
                            document.write("x");
                        case 'd':
                            document.write("w");
                        case 'e':
                            document.write("v");
                        case 'f':
                            document.write("u");
                        case 'g':
                            document.write("t");
                        case 'h':
                            document.write("s");
                        case 'i':
                            document.write("r");
                        case 'j':
                            document.write("q");
                        case 'k':
                            document.write("p");
                        case 'l':
                            document.write("o");
                        case 'm':
                            document.write("n");
                        case 'n':
                            document.write("m");
                        case 'o':
                            document.write("l");
                        case 'p':
                            document.write("k");
                        case 'q':
                            document.write("j");
                        case 'r':
                            document.write("i");
                        case 's':
                            document.write("h");
                        case 't':
                            document.write("g");
                        case 'u':
                            document.write("f");
                        case 'v':
                            document.write("e");
                        case 'w':
                            document.write("d");
                        case 'x':
                            document.write("c");
                        case 'y':
                            document.write("b");
                        case 'z':
                            document.write("a");
                        case '1':
                            document.write("1");
                        default:
                            document.write("");
                        }
                    } else if (cryptography = At - bash) {
                        switch (Array[c]) {
                        case 'a':
                            document.write("z");
                        case 'b':
                            document.write("y");
                        case 'c':
                            document.write("x");
                        case 'd':
                            document.write("w");
                        case 'e':
                            document.write("v");
                        case 'f':
                            document.write("u");
                        case 'g':
                            document.write("t");
                        case 'h':
                            document.write("s");
                        case 'i':
                            document.write("r");
                        case 'j':
                            document.write("q");
                        case 'k':
                            document.write("p");
                        case 'l':
                            document.write("o");
                        case 'm':
                            document.write("n");
                        case 'n':
                            document.write("m");
                        case 'o':
                            document.write("l");
                        case 'p':
                            document.write("k");
                        case 'q':
                            document.write("j");
                        case 'r':
                            document.write("i");
                        case 's':
                            document.write("h");
                        case 't':
                            document.write("g");
                        case 'u':
                            document.write("f");
                        case 'v':
                            document.write("e");
                        case 'w':
                            document.write("d");
                        case 'x':
                            document.write("c");
                        case 'y':
                            document.write("b");
                        case 'z':
                            document.write("a");
                        case '1':
                            document.write("1");
                        default:
                            document.write("");
                        }
                    } else if (cryptography = Ach - bi) {
                        switch (Array[c]) {
                        case 'a':
                            document.write("z");
                        case 'b':
                            document.write("y");
                        case 'c':
                            document.write("x");
                        case 'd':
                            document.write("w");
                        case 'e':
                            document.write("v");
                        case 'f':
                            document.write("u");
                        case 'g':
                            document.write("t");
                        case 'h':
                            document.write("s");
                        case 'i':
                            document.write("r");
                        case 'j':
                            document.write("q");
                        case 'k':
                            document.write("p");
                        case 'l':
                            document.write("o");
                        case 'm':
                            document.write("n");
                        case 'n':
                            document.write("m");
                        case 'o':
                            document.write("l");
                        case 'p':
                            document.write("k");
                        case 'q':
                            document.write("j");
                        case 'r':
                            document.write("i");
                        case 's':
                            document.write("h");
                        case 't':
                            document.write("g");
                        case 'u':
                            document.write("f");
                        case 'v':
                            document.write("e");
                        case 'w':
                            document.write("d");
                        case 'x':
                            document.write("c");
                        case 'y':
                            document.write("b");
                        case 'z':
                            document.write("a");
                        case '1':
                            document.write("1");
                        default:
                            document.write("");
                        }
                    } else if (cryptography = Ayik - becher) {
                        switch (Array[c]) {
                        case 'a':
                            document.write("z");
                        case 'b':
                            document.write("y");
                        case 'c':
                            document.write("x");
                        case 'd':
                            document.write("w");
                        case 'e':
                            document.write("v");
                        case 'f':
                            document.write("u");
                        case 'g':
                            document.write("t");
                        case 'h':
                            document.write("s");
                        case 'i':
                            document.write("r");
                        case 'j':
                            document.write("q");
                        case 'k':
                            document.write("p");
                        case 'l':
                            document.write("o");
                        case 'm':
                            document.write("n");
                        case 'n':
                            document.write("m");
                        case 'o':
                            document.write("l");
                        case 'p':
                            document.write("k");
                        case 'q':
                            document.write("j");
                        case 'r':
                            document.write("i");
                        case 's':
                            document.write("h");
                        case 't':
                            document.write("g");
                        case 'u':
                            document.write("f");
                        case 'v':
                            document.write("e");
                        case 'w':
                            document.write("d");
                        case 'x':
                            document.write("c");
                        case 'y':
                            document.write("b");
                        case 'z':
                            document.write("a");
                        case '1':
                            document.write("1");
                        default:
                            document.write("");
                        }
                    } else if (cryptography = Achas - beta) {
                        switch (Array[c]) {
                        case 'a':
                            document.write("z");
                        case 'b':
                            document.write("y");
                        case 'c':
                            document.write("x");
                        case 'd':
                            document.write("w");
                        case 'e':
                            document.write("v");
                        case 'f':
                            document.write("u");
                        case 'g':
                            document.write("t");
                        case 'h':
                            document.write("s");
                        case 'i':
                            document.write("r");
                        case 'j':
                            document.write("q");
                        case 'k':
                            document.write("p");
                        case 'l':
                            document.write("o");
                        case 'm':
                            document.write("n");
                        case 'n':
                            document.write("m");
                        case 'o':
                            document.write("l");
                        case 'p':
                            document.write("k");
                        case 'q':
                            document.write("j");
                        case 'r':
                            document.write("i");
                        case 's':
                            document.write("h");
                        case 't':
                            document.write("g");
                        case 'u':
                            document.write("f");
                        case 'v':
                            document.write("e");
                        case 'w':
                            document.write("d");
                        case 'x':
                            document.write("c");
                        case 'y':
                            document.write("b");
                        case 'z':
                            document.write("a");
                        case '1':
                            document.write("1");
                        default:
                            document.write("");
                        }
                    } else if (cryptography = At - bach9 - 9 - 4) {
                        switch (Array[c]) {
                        case 'a':
                            document.write("z");
                        case 'b':
                            document.write("y");
                        case 'c':
                            document.write("x");
                        case 'd':
                            document.write("w");
                        case 'e':
                            document.write("v");
                        case 'f':
                            document.write("u");
                        case 'g':
                            document.write("t");
                        case 'h':
                            document.write("s");
                        case 'i':
                            document.write("r");
                        case 'j':
                            document.write("q");
                        case 'k':
                            document.write("p");
                        case 'l':
                            document.write("o");
                        case 'm':
                            document.write("n");
                        case 'n':
                            document.write("m");
                        case 'o':
                            document.write("l");
                        case 'p':
                            document.write("k");
                        case 'q':
                            document.write("j");
                        case 'r':
                            document.write("i");
                        case 's':
                            document.write("h");
                        case 't':
                            document.write("g");
                        case 'u':
                            document.write("f");
                        case 'v':
                            document.write("e");
                        case 'w':
                            document.write("d");
                        case 'x':
                            document.write("c");
                        case 'y':
                            document.write("b");
                        case 'z':
                            document.write("a");
                        case '1':
                            document.write("1");
                        default:
                            document.write("");
                        }
                    } else if (cryptography = At - bach9 - 9 - 9) {
                        switch (Array[c]) {
                        case 'a':
                            document.write("z");
                        case 'b':
                            document.write("y");
                        case 'c':
                            document.write("x");
                        case 'd':
                            document.write("w");
                        case 'e':
                            document.write("v");
                        case 'f':
                            document.write("u");
                        case 'g':
                            document.write("t");
                        case 'h':
                            document.write("s");
                        case 'i':
                            document.write("r");
                        case 'j':
                            document.write("q");
                        case 'k':
                            document.write("p");
                        case 'l':
                            document.write("o");
                        case 'm':
                            document.write("n");
                        case 'n':
                            document.write("m");
                        case 'o':
                            document.write("l");
                        case 'p':
                            document.write("k");
                        case 'q':
                            document.write("j");
                        case 'r':
                            document.write("i");
                        case 's':
                            document.write("h");
                        case 't':
                            document.write("g");
                        case 'u':
                            document.write("f");
                        case 'v':
                            document.write("e");
                        case 'w':
                            document.write("d");
                        case 'x':
                            document.write("c");
                        case 'y':
                            document.write("b");
                        case 'z':
                            document.write("a");
                        case '1':
                            document.write("1");
                        default:
                            document.write("");
                        }
                    } else {
                        switch (Array[c]) {
                        case 'a':
                            document.write("z");
                        case 'b':
                            document.write("y");
                        case 'c':
                            document.write("x");
                        case 'd':
                            document.write("w");
                        case 'e':
                            document.write("v");
                        case 'f':
                            document.write("u");
                        case 'g':
                            document.write("t");
                        case 'h':
                            document.write("s");
                        case 'i':
                            document.write("r");
                        case 'j':
                            document.write("q");
                        case 'k':
                            document.write("p");
                        case 'l':
                            document.write("o");
                        case 'm':
                            document.write("n");
                        case 'n':
                            document.write("m");
                        case 'o':
                            document.write("l");
                        case 'p':
                            document.write("k");
                        case 'q':
                            document.write("j");
                        case 'r':
                            document.write("i");
                        case 's':
                            document.write("h");
                        case 't':
                            document.write("g");
                        case 'u':
                            document.write("f");
                        case 'v':
                            document.write("e");
                        case 'w':
                            document.write("d");
                        case 'x':
                            document.write("c");
                        case 'y':
                            document.write("b");
                        case 'z':
                            document.write("a");
                        case '1':
                            document.write("1");
                        default:
                            document.write("");
                        }
                    };
                }
            },
        });
    }
    $("#j_0").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_0_beforeshow();
    });
    if (runBeforeShow) {
        j_0_beforeshow();
    } else {
        j_0_onLoad();
    }
}
$("#j_0").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_0_js();
});